
package com.example.system_c.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CWebServiceService", targetNamespace = "http://service.system_c.example.com/", wsdlLocation = "http://localhost:8101/Service/getCWebService?wsdl")
public class CWebServiceService
    extends Service
{

    private final static URL CWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CWEBSERVICESERVICE_EXCEPTION;
    private final static QName CWEBSERVICESERVICE_QNAME = new QName("http://service.system_c.example.com/", "CWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8101/Service/getCWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CWEBSERVICESERVICE_WSDL_LOCATION = url;
        CWEBSERVICESERVICE_EXCEPTION = e;
    }

    public CWebServiceService() {
        super(__getWsdlLocation(), CWEBSERVICESERVICE_QNAME);
    }

    public CWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CWEBSERVICESERVICE_QNAME, features);
    }

    public CWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, CWEBSERVICESERVICE_QNAME);
    }

    public CWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CWEBSERVICESERVICE_QNAME, features);
    }

    public CWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CWebService
     */
    @WebEndpoint(name = "CWebServicePort")
    public CWebService getCWebServicePort() {
        return super.getPort(new QName("http://service.system_c.example.com/", "CWebServicePort"), CWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CWebService
     */
    @WebEndpoint(name = "CWebServicePort")
    public CWebService getCWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.system_c.example.com/", "CWebServicePort"), CWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CWEBSERVICESERVICE_EXCEPTION!= null) {
            throw CWEBSERVICESERVICE_EXCEPTION;
        }
        return CWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
