
package com.example.system_c.service;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@javax.jws.WebService(name = "WebService", targetNamespace = "http://service.system_c.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CWebService")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CWebService", targetNamespace = "http://service.system_c.example.com/", className = "com.example.system_c.service.CWebService")
    @ResponseWrapper(localName = "CWebServiceResponse", targetNamespace = "http://service.system_c.example.com/", className = "com.example.system_c.service.CWebServiceResponse")
    @Action(input = "http://service.system_c.example.com/WebService/CWebServiceRequest", output = "http://service.system_c.example.com/WebService/CWebServiceResponse")
    public String cWebService();

}
